// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/contrib/entgql/internal/todo/ent/predicate"
	"entgo.io/contrib/entgql/internal/todo/ent/scores"
	"entgo.io/contrib/entgql/internal/todo/ent/scoresv1"
	"entgo.io/contrib/entgql/internal/todo/ent/scoresv2"
	"entgo.io/contrib/entgql/internal/todo/ent/todo"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScoresQuery is the builder for querying Scores entities.
type ScoresQuery struct {
	config
	ctx           *QueryContext
	order         []OrderFunc
	inters        []Interceptor
	predicates    []predicate.Scores
	withTodo      *TodoQuery
	withScoresV1  *ScoresV1Query
	withScoresV2  *ScoresV2Query
	withFKs       bool
	modifiers     []func(*sql.Selector)
	loadTotal     []func(context.Context, []*Scores) error
	withNamedTodo map[string]*TodoQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ScoresQuery builder.
func (sq *ScoresQuery) Where(ps ...predicate.Scores) *ScoresQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *ScoresQuery) Limit(limit int) *ScoresQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *ScoresQuery) Offset(offset int) *ScoresQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *ScoresQuery) Unique(unique bool) *ScoresQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *ScoresQuery) Order(o ...OrderFunc) *ScoresQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryTodo chains the current query on the "todo" edge.
func (sq *ScoresQuery) QueryTodo() *TodoQuery {
	query := (&TodoClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scores.Table, scores.FieldID, selector),
			sqlgraph.To(todo.Table, todo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, scores.TodoTable, scores.TodoColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryScoresV1 chains the current query on the "ScoresV1" edge.
func (sq *ScoresQuery) QueryScoresV1() *ScoresV1Query {
	query := (&ScoresV1Client{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scores.Table, scores.FieldID, selector),
			sqlgraph.To(scoresv1.Table, scoresv1.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scores.ScoresV1Table, scores.ScoresV1Column),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryScoresV2 chains the current query on the "ScoresV2" edge.
func (sq *ScoresQuery) QueryScoresV2() *ScoresV2Query {
	query := (&ScoresV2Client{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scores.Table, scores.FieldID, selector),
			sqlgraph.To(scoresv2.Table, scoresv2.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scores.ScoresV2Table, scores.ScoresV2Column),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Scores entity from the query.
// Returns a *NotFoundError when no Scores was found.
func (sq *ScoresQuery) First(ctx context.Context) (*Scores, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{scores.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *ScoresQuery) FirstX(ctx context.Context) *Scores {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Scores ID from the query.
// Returns a *NotFoundError when no Scores ID was found.
func (sq *ScoresQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{scores.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *ScoresQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Scores entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Scores entity is found.
// Returns a *NotFoundError when no Scores entities are found.
func (sq *ScoresQuery) Only(ctx context.Context) (*Scores, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{scores.Label}
	default:
		return nil, &NotSingularError{scores.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *ScoresQuery) OnlyX(ctx context.Context) *Scores {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Scores ID in the query.
// Returns a *NotSingularError when more than one Scores ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *ScoresQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{scores.Label}
	default:
		err = &NotSingularError{scores.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *ScoresQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ScoresSlice.
func (sq *ScoresQuery) All(ctx context.Context) ([]*Scores, error) {
	ctx = setContextOp(ctx, sq.ctx, "All")
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Scores, *ScoresQuery]()
	return withInterceptors[[]*Scores](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *ScoresQuery) AllX(ctx context.Context) []*Scores {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Scores IDs.
func (sq *ScoresQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, sq.ctx, "IDs")
	if err := sq.Select(scores.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *ScoresQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *ScoresQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, "Count")
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*ScoresQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *ScoresQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *ScoresQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, "Exist")
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *ScoresQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ScoresQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *ScoresQuery) Clone() *ScoresQuery {
	if sq == nil {
		return nil
	}
	return &ScoresQuery{
		config:       sq.config,
		ctx:          sq.ctx.Clone(),
		order:        append([]OrderFunc{}, sq.order...),
		inters:       append([]Interceptor{}, sq.inters...),
		predicates:   append([]predicate.Scores{}, sq.predicates...),
		withTodo:     sq.withTodo.Clone(),
		withScoresV1: sq.withScoresV1.Clone(),
		withScoresV2: sq.withScoresV2.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithTodo tells the query-builder to eager-load the nodes that are connected to
// the "todo" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *ScoresQuery) WithTodo(opts ...func(*TodoQuery)) *ScoresQuery {
	query := (&TodoClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withTodo = query
	return sq
}

// WithScoresV1 tells the query-builder to eager-load the nodes that are connected to
// the "ScoresV1" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *ScoresQuery) WithScoresV1(opts ...func(*ScoresV1Query)) *ScoresQuery {
	query := (&ScoresV1Client{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withScoresV1 = query
	return sq
}

// WithScoresV2 tells the query-builder to eager-load the nodes that are connected to
// the "ScoresV2" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *ScoresQuery) WithScoresV2(opts ...func(*ScoresV2Query)) *ScoresQuery {
	query := (&ScoresV2Client{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withScoresV2 = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (sq *ScoresQuery) GroupBy(field string, fields ...string) *ScoresGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ScoresGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = scores.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (sq *ScoresQuery) Select(fields ...string) *ScoresSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &ScoresSelect{ScoresQuery: sq}
	sbuild.label = scores.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ScoresSelect configured with the given aggregations.
func (sq *ScoresQuery) Aggregate(fns ...AggregateFunc) *ScoresSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *ScoresQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !scores.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *ScoresQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Scores, error) {
	var (
		nodes       = []*Scores{}
		withFKs     = sq.withFKs
		_spec       = sq.querySpec()
		loadedTypes = [3]bool{
			sq.withTodo != nil,
			sq.withScoresV1 != nil,
			sq.withScoresV2 != nil,
		}
	)
	if sq.withScoresV1 != nil || sq.withScoresV2 != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, scores.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Scores).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Scores{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withTodo; query != nil {
		if err := sq.loadTodo(ctx, query, nodes,
			func(n *Scores) { n.Edges.Todo = []*Todo{} },
			func(n *Scores, e *Todo) { n.Edges.Todo = append(n.Edges.Todo, e) }); err != nil {
			return nil, err
		}
	}
	if query := sq.withScoresV1; query != nil {
		if err := sq.loadScoresV1(ctx, query, nodes, nil,
			func(n *Scores, e *ScoresV1) { n.Edges.ScoresV1 = e }); err != nil {
			return nil, err
		}
	}
	if query := sq.withScoresV2; query != nil {
		if err := sq.loadScoresV2(ctx, query, nodes, nil,
			func(n *Scores, e *ScoresV2) { n.Edges.ScoresV2 = e }); err != nil {
			return nil, err
		}
	}
	for name, query := range sq.withNamedTodo {
		if err := sq.loadTodo(ctx, query, nodes,
			func(n *Scores) { n.appendNamedTodo(name) },
			func(n *Scores, e *Todo) { n.appendNamedTodo(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range sq.loadTotal {
		if err := sq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *ScoresQuery) loadTodo(ctx context.Context, query *TodoQuery, nodes []*Scores, init func(*Scores), assign func(*Scores, *Todo)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Scores)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Todo(func(s *sql.Selector) {
		s.Where(sql.InValues(scores.TodoColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.scores_todo
		if fk == nil {
			return fmt.Errorf(`foreign-key "scores_todo" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "scores_todo" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (sq *ScoresQuery) loadScoresV1(ctx context.Context, query *ScoresV1Query, nodes []*Scores, init func(*Scores), assign func(*Scores, *ScoresV1)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Scores)
	for i := range nodes {
		if nodes[i].scores_v1_scores == nil {
			continue
		}
		fk := *nodes[i].scores_v1_scores
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(scoresv1.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "scores_v1_scores" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (sq *ScoresQuery) loadScoresV2(ctx context.Context, query *ScoresV2Query, nodes []*Scores, init func(*Scores), assign func(*Scores, *ScoresV2)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Scores)
	for i := range nodes {
		if nodes[i].scores_v2_scores == nil {
			continue
		}
		fk := *nodes[i].scores_v2_scores
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(scoresv2.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "scores_v2_scores" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sq *ScoresQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *ScoresQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   scores.Table,
			Columns: scores.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: scores.FieldID,
			},
		},
		From:   sq.sql,
		Unique: true,
	}
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scores.FieldID)
		for i := range fields {
			if fields[i] != scores.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *ScoresQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(scores.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = scores.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedTodo tells the query-builder to eager-load the nodes that are connected to the "todo"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (sq *ScoresQuery) WithNamedTodo(name string, opts ...func(*TodoQuery)) *ScoresQuery {
	query := (&TodoClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if sq.withNamedTodo == nil {
		sq.withNamedTodo = make(map[string]*TodoQuery)
	}
	sq.withNamedTodo[name] = query
	return sq
}

// ScoresGroupBy is the group-by builder for Scores entities.
type ScoresGroupBy struct {
	selector
	build *ScoresQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *ScoresGroupBy) Aggregate(fns ...AggregateFunc) *ScoresGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *ScoresGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, "GroupBy")
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScoresQuery, *ScoresGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *ScoresGroupBy) sqlScan(ctx context.Context, root *ScoresQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ScoresSelect is the builder for selecting fields of Scores entities.
type ScoresSelect struct {
	*ScoresQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *ScoresSelect) Aggregate(fns ...AggregateFunc) *ScoresSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *ScoresSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, "Select")
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScoresQuery, *ScoresSelect](ctx, ss.ScoresQuery, ss, ss.inters, v)
}

func (ss *ScoresSelect) sqlScan(ctx context.Context, root *ScoresQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
